### ISSUE TITLE
Parametrizing fixtures and test functions, DRY!

### ISSUE THREAD

**Issue by Murthy10** [scriptcoffee/JassBot#7]
Some of your tests do have a common pattern which should ring the alarm bells of every software engineer :)

The solution is "Parametrizing fixtures and test functions", have a look at the following:
https://docs.pytest.org/en/latest/parametrize.html

https://github.com/scriptcoffee/JassBot/blob/af185d7d858fc0ab07c6a496ad6925212ce23935/test/test_card_parser.py#L19

**Comment by andieder** [comment]
Done.
